### ISSUE TITLE
[功能改进]: 大佬可以build一个非debian镜像吗？

### ISSUE THREAD

**Issue by 91651** [demigody/nas-tools#2]
### 当前程序版本

3.3.18

### 功能改进

使用了一下大佬的镜像，功能相比其他镜像更完整。
希望能build一个非debian镜像容器，目前debian的镜像体积还是挺大的，希望能减小容器体积。

**Comment by 91651** [comment]
看了下大佬不是没有发布Alpine版本镜像，而是Actions在执行过程中报错了。
报错原因是github服务器无法访问https://dl.minio.org.cn， 将其更换为https://dl.minio.io就行了
已经测试编译通过。

**Comment by 91651** [comment]
测试发现两个问题
1、索引器中没有MT
2、 刷流没有免费类型选择

**Comment by demigody** [comment]
依稀记得那是个周五的下午，点击开始构建之后就奔回家gaming了，根本没注意是否成功。以为构建脚本没改就肯定没问题，前两天看到nt里一个新入库的都没有才看看日志，果然狠狠的打脸了。
1.已修复索引器中没有MT的问题。
2.有的网站没有2xfree，就会没有免费类型选择。

**Comment by 91651** [comment]
> 依稀记得那是个周五的下午，点击开始构建之后就奔回家gaming了，根本没注意是否成功。以为构建脚本没改就肯定没问题，前两天看到nt里一个新入库的都没有才看看日志，果然狠狠的打脸了。 1.已修复索引器中没有MT的问题。 2.有的网站没有2xfree，就会没有免费类型选择。

哈哈哈，我后来研究了一下，然后重新打包了镜像。

目前刷流还有些问题，会下载到收费的种子，还没来得及定位。大佬有时间可以瞅瞅

**Comment by demigody** [comment]
还是mt改了请求路径的锅，v3.3.19已修复。
